In [1]:
import pandas as pd

#subway data
df1 = pd.read_csv('../raw/subway/subway_2020.csv')
df2 = pd.read_csv('../raw/subway/subway_2021.csv')
df3 = pd.read_csv('../raw/subway/subway_2022.csv')
df4 = pd.read_csv('../raw/subway/subway_2023.csv')
df5 = pd.read_csv('../raw/subway/subway_2024.csv')
df6 = pd.read_csv('../raw/subway/subway_2025.csv')

In [2]:
print(df1.info())
print(df2.info())
print(df3.info())
print(df4.info())
print(df5.info())
print(df6.info())

<class 'pandas.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1339 non-null   str
 1   Time       1339 non-null   str
 2   Day        1339 non-null   str
 3   Station    1339 non-null   str
 4   Code       1339 non-null   str
 5   Min Delay  1339 non-null   int64
 6   Min Gap    1339 non-null   int64
 7   Bound      1020 non-null   str
 8   Line       1339 non-null   str
 9   Vehicle    1339 non-null   int64
dtypes: int64(3), str(7)
memory usage: 165.2 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 1216 entries, 0 to 1215
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1216 non-null   str
 1   Time       1216 non-null   str
 2   Day        1216 non-null   str
 3   Station    1216 non-null   str
 4   Code       1216 non-null   str
 5   Min Delay  1216 non-null   int64
 6   Min Gap    1216 non-null   int64
 7   Bound      924 non-null    str
 8   Line       1212 non-null   str
 9   Vehicle    1216 non-null   int64
dtypes: int64(3), str(7)
memory usage: 150.1 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 19895 entries, 0 to 19894
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       19895 non-null  str
 1   Time       19895 non-null  str
 2   Day        19895 non-null  str
 3   Station    19895 non-null  str
 4   Code       19895 non-null  str
 5   Min Delay  19895 non-null  int64
 6   Min Gap    19895 non-null  int64
 7   Bound      14349 non-null  str
 8   Line       19856 non-null  str
 9   Vehicle    19895 non-null  int64
dtypes: int64(3), str(7)
memory usage: 2.4 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 22949 entries, 0 to 22948
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       22949 non-null  str
 1   Time       22949 non-null  str
 2   Day        22949 non-null  str
 3   Station    22949 non-null  str
 4   Code       22949 non-null  str
 5   Min Delay  22949 non-null  int64
 6   Min Gap    22949 non-null  int64
 7   Bound      14423 non-null  str
 8   Line       22901 non-null  str
 9   Vehicle    22949 non-null  int64
dtypes: int64(3), str(7)
memory usage: 2.8 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 26467 entries, 0 to 26466
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       26467 non-null  str
 1   Time       26467 non-null  str
 2   Day        26467 non-null  str
 3   Station    26467 non-null  str
 4   Code       26467 non-null  str
 5   Min Delay  26467 non-null  int64
 6   Min Gap    26467 non-null  int64
 7   Bound      16947 non-null  str
 8   Line       26423 non-null  str
 9   Vehicle    26467 non-null  int64
dtypes: int64(3), str(7)
memory usage: 3.2 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 28191 entries, 0 to 28190
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   _id        28191 non-null  int64
 1   Date       28191 non-null  str
 2   Time       28191 non-null  str
 3   Day        28191 non-null  str
 4   Station    28191 non-null  str
 5   Code       28191 non-null  str
 6   Min Delay  28191 non-null  int64
 7   Min Gap    28191 non-null  int64
 8   Bound      17961 non-null  str
 9   Line       28116 non-null  str
 10  Vehicle    28191 non-null  int64
dtypes: int64(4), str(7)
memory usage: 3.6 MB
None

In [3]:
#only df6 has a extra column that can be dropped
df6 = df6.drop(columns=['_id'])

In [4]:
dfs = [df1, df2, df3, df4, df5, df6]
if all(set(dfs[0].columns) == set(df.columns) for df in dfs):
    print("All DataFrames have the same columns.")
else:
    print("Some DataFrames have different columns.")

All DataFrames have the same columns.

In [5]:
df = pd.concat([df1,df2,df3,df4,df5,df6], ignore_index=True)

In [6]:
df

,Date,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Line,Vehicle
0,2020-01-01,01:18,Wednesday,KENNEDY SRT STATION,SRDP,8,13,N,SRT,3025
1,2020-01-01,01:27,Wednesday,SHEPPARD WEST STATION,MUI,7,12,S,YU,5591
2,2020-01-01,02:22,Wednesday,MAIN STREET STATION,EUNT,3,7,W,BD,5371
3,2020-01-01,03:54,Wednesday,KIPLING STATION,MUIS,0,0,E,BD,5243
4,2020-01-01,08:07,Wednesday,KEELE STATION,MUNOA,4,9,W,BD,5011
...,...,...,...,...,...,...,...,...,...,...
100052,2026-01-31,01:54,Saturday,BLOOR STATION,MUIS,0,0,NaN,YU,0
100053,2026-01-31,01:59,Saturday,YORK MILLS STATION,PUTO,12,18,N,YU,5761
100054,2026-01-31,03:14,Saturday,BAYVIEW STATION,PUTO,0,0,NaN,SHP,0
100055,2026-01-31,06:00,Saturday,SHEPPARD-YONGE STATION,MUCP,0,0,NaN,SHP,0
100056,2026-01-31,09:46,Saturday,DON MILLS STATION,MUO,0,0,NaN,SHP,0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100057 entries, 0 to 100056
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Date       100057 non-null  str
 1   Time       100057 non-null  str
 2   Day        100057 non-null  str
 3   Station    100057 non-null  str
 4   Code       100057 non-null  str
 5   Min Delay  100057 non-null  int64
 6   Min Gap    100057 non-null  int64
 7   Bound      65624 non-null   str
 8   Line       99847 non-null   str
 9   Vehicle    100057 non-null  int64
dtypes: int64(3), str(7)
memory usage: 12.0 MB

In [8]:
#bound and line has NULL
df.Bound.unique()

<ArrowStringArray>
['N', 'S', 'W', 'E', nan, 'B']
Length: 6, dtype: str

In [11]:
codes = pd.read_csv('../raw/subway/subway_code.csv')
code_map = dict(zip(codes['CODE'], codes['DESCRIPTION']))
df['Incident'] = df['Code'].map(code_map)

In [13]:
df = df.drop(columns=['Code'])

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100057 entries, 0 to 100056
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Date       100057 non-null  str
 1   Time       100057 non-null  str
 2   Day        100057 non-null  str
 3   Station    100057 non-null  str
 4   Min Delay  100057 non-null  int64
 5   Min Gap    100057 non-null  int64
 6   Bound      65624 non-null   str
 7   Line       99847 non-null   str
 8   Vehicle    100057 non-null  int64
 9   Incident   97744 non-null   str
dtypes: int64(3), str(7)
memory usage: 14.6 MB

In [16]:
df.Incident.isnull().sum()

np.int64(2313)

In [19]:
df[df.Incident.isnull()]

,Date,Time,Day,Station,Min Delay,Min Gap,Bound,Line,Vehicle,Incident
0,2020-01-01,01:18,Wednesday,KENNEDY SRT STATION,8,13,N,SRT,3025,NaN
29,2020-01-02,02:18,Thursday,SCARBOROUGH CTR STATIO,0,0,NaN,SRT,0,NaN
44,2020-01-02,12:23,Thursday,KENNEDY SRT STATION,0,0,N,SRT,3007,NaN
76,2020-01-03,08:17,Friday,MCCOWAN STATION,5,10,S,SRT,3004,NaN
99,2020-01-03,18:29,Friday,MIDLAND STATION,0,0,S,SRT,3010,NaN
...,...,...,...,...,...,...,...,...,...,...
99382,2026-01-25,08:27,Sunday,MUSEUM STATION,18,0,N,YU,5461,NaN
99602,2026-01-27,06:02,Tuesday,ST ANDREW STATION,10,0,N,YU,6011,NaN
99916,2026-01-30,05:56,Friday,EGLINTON STATION,10,0,N,YU,5706,NaN
100053,2026-01-31,01:59,Saturday,YORK MILLS STATION,12,18,N,YU,5761,NaN
100054,2026-01-31,03:14,Saturday,BAYVIEW STATION,0,0,NaN,SHP,0,NaN

In [20]:
#~2.3% can be dropped with no major impact to the prediction model
df = df.dropna(subset='Incident')

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 97744 entries, 1 to 100056
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       97744 non-null  str
 1   Time       97744 non-null  str
 2   Day        97744 non-null  str
 3   Station    97744 non-null  str
 4   Min Delay  97744 non-null  int64
 5   Min Gap    97744 non-null  int64
 6   Bound      64144 non-null  str
 7   Line       97537 non-null  str
 8   Vehicle    97744 non-null  int64
 9   Incident   97744 non-null  str
dtypes: int64(3), str(7)
memory usage: 15.1 MB

In [23]:
#Bound and line are null
df[df.Bound.isnull()]

,Date,Time,Day,Station,Min Delay,Min Gap,Bound,Line,Vehicle,Incident
13,2020-01-01,14:25,Wednesday,DUNDAS WEST STATION,0,0,NaN,BD,0,INJURED/ILL CUSTOMER IN STATION - TRANSPORTED
19,2020-01-01,19:46,Wednesday,DUNDAS STATION,0,0,NaN,YU,0,INJURED/ILL CUSTOMER IN STATION â MEDICAL AI...
20,2020-01-01,20:12,Wednesday,VICTORIA PARK STATION,0,0,NaN,BD,0,ANY ESCL. OR ELEV. INCIDENT â TRANSPORTED OR...
21,2020-01-01,22:00,Wednesday,YONGE-UNIVERSITY & BLO,0,0,NaN,YU/BD,0,MISCELLANEOUS OTHER
26,2020-01-02,00:37,Thursday,WARDEN STATION,0,0,NaN,BD,0,INJURED/ILL CUSTOMER IN STATION - TRANSPORTED
...,...,...,...,...,...,...,...,...,...,...
100049,2026-01-31,00:24,Saturday,UNION STATION,0,0,NaN,YU,0,INJURED/ILL CUSTOMER IN STATION â MEDICAL AI...
100050,2026-01-31,01:13,Saturday,QUEEN STATION,0,0,NaN,YU,0,SECURITY OTHER
100052,2026-01-31,01:54,Saturday,BLOOR STATION,0,0,NaN,YU,0,INJURED/ILL CUSTOMER IN STATION - TRANSPORTED
100055,2026-01-31,06:00,Saturday,SHEPPARD-YONGE STATION,0,0,NaN,SHP,0,CLOSURES - PLANNED
100056,2026-01-31,09:46,Saturday,DON MILLS STATION,0,0,NaN,SHP,0,MISCELLANEOUS OTHER

In [24]:
#most of the incidents are at garage or emergency so must not be dropped 
#filling in with unknown
#also creating a binary feature for known/unknown
df['Bound'] = df['Bound'].fillna('UNKNOWN')
df['Direction_known'] = (df['Bound'] != 'UNKNOWN').astype(int)

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 97744 entries, 1 to 100056
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             97744 non-null  str
 1   Time             97744 non-null  str
 2   Day              97744 non-null  str
 3   Station          97744 non-null  str
 4   Min Delay        97744 non-null  int64
 5   Min Gap          97744 non-null  int64
 6   Bound            97744 non-null  str
 7   Line             97537 non-null  str
 8   Vehicle          97744 non-null  int64
 9   Incident         97744 non-null  str
 10  Direction_known  97744 non-null  int64
dtypes: int64(4), str(7)
memory usage: 16.0 MB

In [26]:
df[df.Line.isnull()]

,Date,Time,Day,Station,Min Delay,Min Gap,Bound,Line,Vehicle,Incident,Direction_known
1834,2021-01-13,15:22,Wednesday,FINCH WEST STATION,3,6,S,NaN,5751,UNSANITARY VEHICLE,1
1852,2021-01-13,22:08,Wednesday,EGLINTON WEST STATION,0,0,UNKNOWN,NaN,0,ANY ESCL. OR ELEV. INCIDENT â TRANSPORTED OR...,0
2383,2021-01-27,22:00,Wednesday,YONGE-UNIVERSITY AND B,0,0,UNKNOWN,NaN,0,MISCELLANEOUS OTHER,0
2384,2021-01-27,23:00,Wednesday,FINCH STATION,0,0,UNKNOWN,NaN,0,MISCELLANEOUS OTHER,0
2839,2022-01-05,00:01,Wednesday,FINCH STATION,0,0,UNKNOWN,NaN,0,DISORDERLY PATRON,0
...,...,...,...,...,...,...,...,...,...,...,...
99231,2026-01-23,10:42,Friday,CHESTER STATION,0,0,E,NaN,0,SECURITY OTHER,1
99275,2026-01-23,22:14,Friday,TMU STATION,0,0,UNKNOWN,NaN,0,DISORDERLY PATRON,0
99318,2026-01-24,12:04,Saturday,GREENWOOD CARHOUSE,0,0,UNKNOWN,NaN,0,INJURED EMPLOYEES,0
99349,2026-01-24,21:33,Saturday,GREENWOOD CAR HOUSE,0,0,UNKNOWN,NaN,5339,GRAFFITI / SCRATCHITI,0
99733,2026-01-28,02:52,Wednesday,N/O SHEPPARD TO FINCH,0,0,UNKNOWN,NaN,0,TRACTION POWER RAIL RELATED PROBLEMS,0

In [27]:
#most of the subs never departed or departed late, dropping for better predictions 
df = df.dropna(subset='Line')

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 97537 entries, 1 to 100056
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             97537 non-null  str
 1   Time             97537 non-null  str
 2   Day              97537 non-null  str
 3   Station          97537 non-null  str
 4   Min Delay        97537 non-null  int64
 5   Min Gap          97537 non-null  int64
 6   Bound            97537 non-null  str
 7   Line             97537 non-null  str
 8   Vehicle          97537 non-null  int64
 9   Incident         97537 non-null  str
 10  Direction_known  97537 non-null  int64
dtypes: int64(4), str(7)
memory usage: 16.0 MB

In [29]:
#97% data intact
df.head()

,Date,Time,Day,Station,Min Delay,Min Gap,Bound,Line,Vehicle,Incident,Direction_known
1,2020-01-01,01:27,Wednesday,SHEPPARD WEST STATION,7,12,S,YU,5591,INJURED/ILL CUSTOMER ON TRAIN â TRANSPORTED,1
2,2020-01-01,02:22,Wednesday,MAIN STREET STATION,3,7,W,BD,5371,EQUIPMENT â NO TROUBLE FOUND,1
3,2020-01-01,03:54,Wednesday,KIPLING STATION,0,0,E,BD,5243,INJURED/ILL CUSTOMER IN STATION - TRANSPORTED,1
4,2020-01-01,08:07,Wednesday,KEELE STATION,4,9,W,BD,5011,NO OPERATOR AVAILABLE â NON ESA RELATED,1
5,2020-01-01,08:10,Wednesday,KEELE STATION,4,8,W,BD,5307,NO OPERATOR AVAILABLE â NON ESA RELATED,1

In [30]:
df = df.rename(columns={
    'Station' : 'Location',
    'Bound'   : 'Direction',
    'Line'    : 'Route',
})

df['Hour']       = pd.to_datetime(df['Time']).dt.hour
df['Minute']     = pd.to_datetime(df['Time']).dt.minute
df['Month']      = pd.to_datetime(df['Date']).dt.month
df['Year']       = pd.to_datetime(df['Date']).dt.year
df['DayOfWeek']  = pd.to_datetime(df['Date']).dt.dayofweek

df['Direction_clean'] = df['Direction'].str.strip().map(pd.Series(DIRECTION_MAP))

df = df.drop(columns=['Date', 'Time'])

/var/folders/6r/5501445946z5p3k2h5qbwvlm0000gn/T/ipykernel_59741/2457719573.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Hour']       = pd.to_datetime(df['Time']).dt.hour
/var/folders/6r/5501445946z5p3k2h5qbwvlm0000gn/T/ipykernel_59741/2457719573.py:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Minute']     = pd.to_datetime(df['Time']).dt.minute

NameError: name 'DIRECTION_MAP' is not defined